### ISSUE TITLE
Positive lookbehind Regex not supported in most browsers

### ISSUE THREAD

**Issue by Cherry** [CraftTweaker/codemirror-mode-zenscript#6]
The regex `/\b(?<=(as\s))[a-zA-Z]+\b/` uses a positive lookbehind, which [isn't supported in Edge, Firefox, Safari, and more](https://caniuse.com/#feat=js-regexp-lookbehind). 

This prevents the module from being included in a build process that builds JS for multiple different browsers, as there's no smart way to polyfill this functionality, and the build process then terminates. 

I'm not entirely sure what the desired functionality here is, but, using:
```zenscript
function removeAllRecipes(item as IItemStack, liquid as ILiquidStack)
```
as a test, this:
```regex
\b(as\s)[a-zA-Z]+\b
```
matches the `as` just fine, without the positive lookbehind.

**Comment by jaredlll08** [comment]
I wish Github sent me an email sooner, I've spent the past 10 minutes trying to get this one highlighting right, your regex was a good base :P
